server:
  port: 8899
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: virtual_thread
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: postgres
    password: qwer@123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    com.application.*: debug

terrain:
  directory: /mnt/share/data/terrain

image:
  directory: D:\test\tile_service\data