server:
  port: 8899
  tomcat:
    threads:
      min-spare: 1
      max: 4
      accept-count: 100000
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: virtual_thread
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
        slave:
          url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
logging:
  level:
    com.application.*: info

terrain:
  directory: /mnt/share/data/terrain

image:
  directory: D:\test\tile_service\data